menambahkan lebih banyak output debug

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -101,13 +101,13 @@ jobs:
 
       - name: Test FTP connection with lftp
         run: |
-          echo "Testing FTP connection with lftp..."
-          lftp -e "set ftp:ssl-allow no; ls; bye" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER || echo "lftp command failed"
-        env:
+         echo "Testing FTP connection with lftp..."
+          lftp -d -e "set ftp:ssl-allow no; ls; bye" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER || echo "lftp command failed"
+          env:
           FTP_SERVER: ftp.siforta.my.id
-          FTP_USERNAME: siforta@siforta.my.id
-          FTP_PASSWORD: Siforta12345
-
+           FTP_USERNAME: siforta@siforta.my.id
+           FTP_PASSWORD: Siforta12345
+    
       - name: Deploy to server via FTP
         run: |
           echo "Deploying to FTP server..."
